### ISSUE TITLE
Improper user input validation and exception handling

### ISSUE THREAD

**Issue by Himan10** [spyboy-productions/Facad1ng#1]
**Description**: So recently I was checking running your code on my machine and it was working fine for the legit URLs, and it provided me the modified phishing URL, which was great. However when I checked your code, there I found out several issues with the functions you've written for validation several inputs. I was able to provide any type of input that doesn't need to be a proper URL or domain name. 

Functions used for validating user input: 
1. `validate_web_url`
2. `validate_custom_domain`
3. `format_phish_keywords` ( I think, it'd be better if you perform some validation here as well, and allow users to only enter a word containing only alphabets and also set a fixed length for phishing keywords). 

**Steps to reproduce**: 
1. git clone the repo.
2. run facad1ng.py
3. for the original link, enter input string `https://///////////////////////////////////////////1`. It'll accept this. 
4. for the custom domain, enter whatever input string that doesn't contain `://` or `/`. For example: `.` (dot) is acceptable as well
5. for the phishing keywords, enter any length of string, it'll get accepted and the script generates URLs with these long keywords. 
6. with the above inputs, your script will raise an exception, and throw the exception on the console. So, it's better if you handle such exceptions and test-cases as well. 

**Screenshots**:
1. Exception not handled properly and input validation
![image](https://github.com/spyboy-productions/Facad1ng/assets/33115688/4f08223c-e179-48c0-a992-2bc8e1b79b25)

2. No fixed length implemented for phishing keywords
![image](https://github.com/spyboy-productions/Facad1ng/assets/33115688/7676b9de-2cd6-4f05-8b02-e755539c6770)

Hope this help, also would you like to allow me to raise a PR for the same? good to contribute a little on such cool projects.

**Comment by thisisshubhamkumar** [comment]
Thanks for checking out the code and for pointing out these issues. Your feedback is valuable!

If you're up for it, we'd love for you to create a pull request with the fixes. 

We'll review it and work together to improve the tool. If you have any questions, feel free to ask.

Cheers

**Comment by Himan10** [comment]
Thanks man for the response. 
Sure, I'll raise a pull request as soon as possible with the fixes as mentioned in the issue #1

Also, I've just one basic question regarding the process of generating tiny URLs, so the masked URLs contain the name of vendors who provide this service, for example: tinyurl. 
so, for users who are into security or aware of phishing links might guess it right by seeing the masked URL, so isn't it possible if somehow the python script crafts a little more so that it becomes little hard to guess by any type of user.

**Comment by thisisshubhamkumar** [comment]
That's a great point you've raised. Masked URLs that contain the vendor's name can potentially be more easily recognized by users who are security-conscious.

To make the masked URLs harder to guess, one approach could be to perform additional encoding on the URL after shortening. Base64 encoding is a good idea, and it can add an extra layer of obfuscation to the URL. You can modify the script to encode the URL using Base64 or another encoding scheme of your choice before appending the custom domain and phishing keywords.

If you decide to implement this change, please feel free to include it in your pull request, and we can review it together. Your contribution will not only enhance the security of the tool but also make it more robust.

**Comment by Himan10** [comment]
Sure, I'll look into it and raise a PR asap. 
Thanks for allowing me to contribute, Cheers 🥂

**Comment by Himan10** [comment]
@thisisshubhamkumar Hi there, sorry for late reply
@Tanyashrvstv will be working on the above given changes, and will raise a PR for this soon.
