### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by profesionalleet1337** [spyboy-productions/Facad1ng#3]
Hey, from my test, the tool didnt' work. Its generated 10 lines maskied url, which is not clickable and useful, I mean the masking option is bugged and didn't work! Could u fix her ?

**Comment by thisisshubhamkumar** [comment]
you need to be more specific, attach a snapshot or type the error that it’s showing.

It’s a pretty straightforward tool, just install requirement and run it.

<img width="537" alt="Screenshot 2023-11-16 at 8 49 12 PM" src="https://github.com/spyboy-productions/Facad1ng/assets/25564020/e56b432f-d11d-4c35-b8f1-eefcdfb77026">

**Comment by profesionalleet1337** [comment]
> you need to be more specific, attach a snapshot or type the error that it’s showing.
> 
> It’s a pretty straightforward tool, just install requirement and run it.
> 
> <img alt="Screenshot 2023-11-16 at 8 49 12 PM" width="537" src="https://user-images.githubusercontent.com/25564020/283962509-e56b432f-d11d-4c35-b8f1-eefcdfb77026.png">

It's functional normal when I type fictional or working website, but when I generate a phishing link from a phishing tool, like zpisher or something like this ( generated with cloudflare for example ) , it doesn't accept the link and doesn't do the mask..

What's I received is this:
 "/home/x/Facad1ng/facad1ng.py", line 102, in <module> short_urls = [shortener.short(web_url) for shortener in shorteners] File "/home/x/Facad1ng/facad1ng.py", line 102, in <listcomp> short_urls = [shortener.short(web_url) for shortener in shorteners] File "/home/x/.local/lib/python3.9/site-packages/pyshorteners/shorteners/tinyurl.py", line 37, in short raise ShorteningErrorException(response.content) pyshorteners.exceptions.ShorteningErrorException: There was an error on trying to short the url: b'Error

**Comment by thisisshubhamkumar** [comment]
This is still not helpful attach a screenshot of the terminal where you pass the URL and other arguments else mention what URL you are passing.

I can only guess either you have not installed requirements or you are passing the localhost URL that you mentioned generated by tool zpisher which is generally not port forwarded URL which will not work on the internet. make sure that the URL you are passing works on the internet(with status 200) else first port forward your localhost.

**Comment by profesionalleet1337** [comment]
> This is still not helpful attach a screenshot of the terminal where you pass the URL and other arguments else mention what URL you are passing.
> 
> I can only guess either you have not installed requirements or you are passing the localhost URL that you mentioned generated by tool zpisher which is generally not port forwarded URL which will not work on the internet. make sure that the URL you are passing works on the internet(with status 200) else first port forward your localhost.

Okay, here : 
![1](https://github.com/spyboy-productions/Facad1ng/assets/103360683/5a970c55-5577-457f-9238-b79d8a3b4863)

I inserted a link generated by other phishing tool - with cloudflear, the link worked, but the tool does not want to mask it, this is what I get as a response..
(If I write a normal website for example or make up something like "www.normalste.com" its working - yes  , but doesn't want to mask those links generated by phishing tools for example, why ? )

**Comment by thisisshubhamkumar** [comment]
As I mentioned before make sure that the URL you are passing works on the internet(www) not only on localhost
https://greatest-headlines-tennessee-lottery.trycloudflare.com/ has no status 200 check on https://httpstatus.io/

trycloudflare.com has also no status of 200 

That’s not a valid URL that URL Shortener can shorten. Try port forwarding if you are hosting phishing URL locally.

Second, don’t put www before domain in the custom domain.

Here’s another example, I am masking the localhost port forwarded NGROK URL, which works perfectly fine.
<img width="680" alt="Screenshot 2023-11-20 at 11 16 42 PM" src="https://github.com/spyboy-productions/Facad1ng/assets/25564020/6f3c27f2-bdf5-4fa3-bb57-d4eb0d30a2d8">

**Comment by profesionalleet1337** [comment]
> https://greatest-headlines-tennessee-lottery.trycloudflare.com/

You explain quite well and in detail! Thank you for that and I understand where the problem is. But, when I use ready-made tools, they just generate this type of links, most of them are based on localhost/cloudflare and so on. There is also an option with ngrock, but it is not preferred and is I think also with some time ( 15   minutes "living link"  , I think it was from memory, which is not ok for phishing ). As a conclusion, the mask only works with sites like this, which is about 200, right ? There is no way to mask such links, like those from ready-made toolkits, if I understand correctly. 
Please apologize me for the bad grammar ! (Do you have a discord/telegram, somewhere where I can keep in touch with you ?)

**Comment by profesionalleet1337** [comment]
> As I mentioned before make sure that the URL you are passing works on the internet(www) not only on localhost https://greatest-headlines-tennessee-lottery.trycloudflare.com/ has no status 200 check on https://httpstatus.io/
> 
> trycloudflare.com has also no status of 200
> 
> That’s not a valid URL that URL Shortener can shorten. Try port forwarding if you are hosting phishing URL locally.
> 
> Second, don’t put www before domain in the custom domain.
> 
> Here’s another example, I am masking the localhost port forwarded NGROK URL, which works perfectly fine. <img alt="Screenshot 2023-11-20 at 11 16 42 PM" width="680" src="https://user-images.githubusercontent.com/25564020/284356272-6f3c27f2-bdf5-4fa3-bb57-d4eb0d30a2d8.png">

You explain quite well and in detail! Thank you for that and I understand where the problem is. But, when I use ready-made tools, they just generate this type of links, most of them are based on localhost/cloudflare and so on. There is also an option with ngrock, but it is not preferred and is I think also with some time ( 15 minutes "living link" , I think it was from memory, which is not ok for phishing ). As a conclusion, the mask only works with sites like this, which is about 200, right ? There is no way to mask such links, like those from ready-made toolkits, if I understand correctly.
Please apologize me for the bad grammar ! (Do you have a discord/telegram, somewhere where I can keep in touch with you ?)

**Comment by thisisshubhamkumar** [comment]
You can reach us on Discord: https://discord.gg/ZChEmMwE8d
We are closing this issue.
