### ISSUE TITLE
Why do I keep getting this error?

### ISSUE THREAD

**Issue by Bootywarrio** [spyboy-productions/Facad1ng#4]
Traceback (most recent call last):
  File "/home/bootywarrior/Facad1ng/facad1ng.py", line 53, in <module>
    s.tinyurl,
AttributeError: 'Shortener' object has no attribute 'tinyurl'

I literally just installed it on Parrot OS

**Comment by thisisshubhamkumar** [comment]
It seems like you haven’t installed `requirements.txt` Go through the readme file and use this command `pip3 install -r requirements.txt` to install requirements.txt.
