### ISSUE TITLE
requirements not installing

### ISSUE THREAD

**Issue by arnavgoyal543** [spyboy-productions/Facad1ng#5]
it showas that the reqiurment has expierd licence and it is not installing. plz help

**Comment by thisisshubhamkumar** [comment]
Attach a screenshot of the error. We have confirmed that the requirements are working correctly. Follow the instructions provided in the readme file or run the program online https://colab.research.google.com/github/spyboy-productions/Facad1ng/blob/main/Facad1ng.ipynb
